import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
import Side_NavBar from "./Components/Side_NavBar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <>
          <ThemeProvider attribute="class" defaultTheme="system">
            <div>
              <Header />
            </div>
            <div className="flex ">
              <Side_NavBar />
              <div className="w-full pt-[56px] sm:p-4">{children}</div>
            </div>
          </ThemeProvider>
        </>
      </body>
    </html>
  );
}
